title: Linus Scheibenreif # your name (or website title) here
logo: "/images/linus_IMG_1741.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi I'm Linus.
  I'm currently a Postdoc with the <a href="https://prs.igp.ethz.ch/">PRS group</a> at ETH Zurich. I obtained my Ph.D. from the <a href="https://ics.unisg.ch/chairs/damian-borth-artificial-intelligence-and-machine-learning/">AI:ML group</a> at the University of St. Gallen (HSG).
  <br><br>
  My work combines Machine Learning and Computer Vision methods with Geospatial Earth Observation. For my Ph.D., I focused on Self-supervised Deep Learning for Earth Observation data.
  <br><br>
  <a href="https://www.github.com/scheibenreif">GitHub</a> <br>
  <a href="https://scholar.google.com/citations?user=9xbMAkcAAAAJ&hl=de">Google Scholar</a> <br>
  <a href="https://www.linkedin.com/in/linus-scheibenreif/">LinkedIn</a> <br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
